services:
  goldentable.database:
    image: postgres:latest
    container_name: GoldenTable.Database
    environment:
      - POSTGRES_DB=goldentable
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d goldentable"]
      interval: 5s
      timeout: 5s
      retries: 5

  goldentable.redis:
    image: redis:latest
    container_name: GoldenTable.Redis
    ports:
      - "6379:6379"

  goldentable.api:
    image: goldentable.api
    container_name: GoldenTable.Api
    build:
      context: .
      dockerfile: GoldenTable.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      goldentable.database:
        condition: service_healthy