// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GoldenTable.Modules.Catalog.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class TagsUpdate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_DishTag_Value",
                schema: "Catalog",
                table: "DishTag",
                column: "Value",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_DishTag_Value",
                schema: "Catalog",
                table: "DishTag");
        }
    }
}
