// <auto-generated />
using System;
using System.Collections.Generic;
using GoldenTable.Modules.Catalog.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoldenTable.Modules.Catalog.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260227131552_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DishDishTag", b =>
                {
                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("DishId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("DishDishTag", "Catalog");
                });

            modelBuilder.Entity("GoldenTable.Modules.Catalog.Domain.Common.Image.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DishId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Images", "Catalog");
                });

            modelBuilder.Entity("GoldenTable.Modules.Catalog.Domain.Dishes.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BasePrice", "GoldenTable.Modules.Catalog.Domain.Dishes.Dish.BasePrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NutritionalInformation", "GoldenTable.Modules.Catalog.Domain.Dishes.Dish.NutritionalInformation#NutritionalValues", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<float>("GramsOfFat");

                            b1.Property<float>("GramsOfProtein");

                            b1.Property<float>("GramsOfSalt");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Energy", "GoldenTable.Modules.Catalog.Domain.Dishes.Dish.NutritionalInformation#NutritionalValues.Energy#Energy", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<float>("Kcal");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "GramsOfCarbohydrates", "GoldenTable.Modules.Catalog.Domain.Dishes.Dish.NutritionalInformation#NutritionalValues.GramsOfCarbohydrates#Carbohydrates", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<float>("OfWhichSugar");

                                    b2.Property<float>("Total");
                                });

                            b1
                                .ToJson("NutritionalInformation")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Dishes", "Catalog");
                });

            modelBuilder.Entity("GoldenTable.Modules.Catalog.Domain.Dishes.ValueObject.DishTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DishTag", "Catalog");
                });

            modelBuilder.Entity("DishDishTag", b =>
                {
                    b.HasOne("GoldenTable.Modules.Catalog.Domain.Dishes.Dish", null)
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenTable.Modules.Catalog.Domain.Dishes.ValueObject.DishTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoldenTable.Modules.Catalog.Domain.Common.Image.Image", b =>
                {
                    b.HasOne("GoldenTable.Modules.Catalog.Domain.Dishes.Dish", null)
                        .WithMany("Images")
                        .HasForeignKey("DishId");

                    b.OwnsOne("GoldenTable.Modules.Catalog.Domain.Common.ValueTypes.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ImageId");

                            b1.ToTable("Images", "Catalog");

                            b1.WithOwner()
                                .HasForeignKey("ImageId");
                        });

                    b.Navigation("Description");
                });

            modelBuilder.Entity("GoldenTable.Modules.Catalog.Domain.Dishes.Dish", b =>
                {
                    b.OwnsOne("GoldenTable.Modules.Catalog.Domain.Common.ValueTypes.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("DishId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DishId");

                            b1.ToTable("Dishes", "Catalog");

                            b1.WithOwner()
                                .HasForeignKey("DishId");
                        });

                    b.OwnsMany("GoldenTable.Modules.Catalog.Domain.Dishes.ValueObject.DishSize", "Sizes", b1 =>
                        {
                            b1.Property<Guid>("DishId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<float>("PriceAdded")
                                .HasColumnType("real");

                            b1.Property<float>("Weight")
                                .HasColumnType("real");

                            b1.HasKey("DishId", "Id");

                            b1.ToTable("DishSize", "Catalog");

                            b1.WithOwner()
                                .HasForeignKey("DishId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("GoldenTable.Modules.Catalog.Domain.Dishes.Dish", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
